name = "Prine"
license = "Apache2"
licenselink = "https://github.com/kris-nova/prine/blob/master/LICENSE"
description = ""
homepage = "https://nivenly.com/"
tags = []
features = []
min_version = "0.41.0"
baseURL = '/'
languageCode = 'en-us'
title = 'Hacking Capitalism'
subtitle = 'Modeling Humans, Computers, and Money'
theme = "prine"

[author]
  name = "Kris Nóva <kris@nivenly.com>"
  homepage = "https://nivenly.com"
  
[params]
    description = "This is an independently published book about modeling the tech industry as a system. Particularly this book will model computers, humans, and money and their subsequent relationships. Understand the alarming state of the tech industry for better or for worse."
    # Love the TikTok
    keywords = "Book, Purchase, Sign up, Author, Download, PDF, Capitalism, Hacking, Tech Industry, Silicon Valley, San Francisco, Bay Area, Exploit, Career, Guide, Humans, Computers, Money, books, booktok, bookish, bookworm, bookrecs, fyp, book, foryou, bookstan"
    ISBN = ""
    twitterURL = "https://twitter.com/krisnova"
    twitterText = "@krisnova"
    githubURL = "https://github.com/kris-nova"
    githubText = "kris-nova"
    discordURL = "https://discord.com/invite/QG27kwx4nf"
    discordText = "Join our official Discord!"
    youtubeURL = "https://www.youtube.com/channel/UCRvH2UexTzcbZRwCS6OxJ3w"
    youtubeText = "Official YouTube channel!"
    settingsURL = "https://nivenly.com"
    settingsText = "Tweak your site's settings."
    copyright = "2022 Kris Nóva"
    googleAnalyticsID = "G-2N5YYN3BX6"
    unfurlLogo = "https://hackingcapitalism.io/img/art.png"
    unfurlCreator = "Kris Nóva"
    unfurlSite = "https://hackingcapitalism.io"
    unfurlTitle = "Hacking Capitalism | A Guide To Exploiting The Tech Industry"

[languages.en.params.logo]
    logoUser = "nova"
    logoHost = "hc"
[languages.en.menu]
    [[languages.en.menu.main]]
        identifier = "readme"
        name = "readme"
        url = "/readme"
